version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9095:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "logs:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
    depends on:
      zookeeper
  clickhouse:
    image: yandex/clickhouse-server
    depends on:
      kafka
  redis:
    image: "redis:alpine"
    depends on:
      postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test  
      POSTGRES_PASSWORD: test
  users:
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_URL: 
    depends_on:
      postgres
      redis
      kafka
  